project:
  type: website
  output-dir: docs

website:
  title: "Gabriela Palomo"
  page-navigation: true
  open-graph: true
  twitter-card: 
    creator: "@gabbspalomo"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "ClipArts"
        href: cliparts.qmd
      - text: "Projects"
        # href: projects.qmd
        menu:
          - text: "Portfolio - Data Visualization"
            #icon: "bug"
            file: projects/portfolio.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Workshops"
      - menu: 
          - text: 'Introduction to ggplot2'
            file: workshops/intro_ggplot2/index.qmd   
    # - text: "CV"
    #   href: cv.qmd
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-CKLD1G1PM7"
    anonymize-ip: true
  page-footer: 'Copyright 2024 Gabriela Palomo-Munoz. All text and images licensed CC-BY-NC 4.0.'

# sidebar:
#   - title: "Projects"
#     style: "docked"
#     background: light
#     contents:
#       - projects.qmd
#       - project-01.qmd
#       - project-02.qmd

format:
  html:
    theme: [Lux, "css/styles.css",  "slides/data_manipulation/tutorial/output_style.scss"]
    toc: true

# comments:
#   giscus:
#     repo: gabspalomo/gabspalomo.github.io

