project:
  type: website
  output-dir: docs

website:
  title: "Gabriela Palomo"
  page-navigation: true
  open-graph: true
  twitter-card: 
    creator: "@gabbspalomo"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "My Digital Notebook"
        href: blog.qmd
      - text: "Silhouettes"
        href: silhouettes.qmd
      - text: "Projects"
        href: projects.qmd
        menu:
          - text: "Project 1"
            #icon: "bug"
            href: projects/project1.qmd
          - text: "Project 2"
            #icon: "chat-right-te
            href: projects/project.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV in pictures"
        href: cv_in_pictures.qmd
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-CKLD1G1PM7"
    anonymize-ip: true

sidebar:
  - title: "Projects"
    style: "docked"
    background: light
    contents:
      - projects.qmd
      - project-01.qmd
      - project-02.qmd

format:
  html:
    theme: Lux
    css: css/styles.css
    toc: true

# comments:
#   giscus:
#     repo: gabspalomo/gabspalomo.github.io

